# Generated by Django 5.1.2 on 2024-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='sliders')),
            ],
        ),
    ]
